# ///////////////////////////////////////////////////////////////
#
# StrikeWorks - data extraction, validation, processing and model
# development tool for underwater passive sensor devices.
#
# ///////////////////////////////////////////////////////////////
"""HTML report builder for a Blade Strike Modelling result.

Deliberately does NOT port the old MVP app's `bsm/report/builder.py`
(a MathJax-equation methodology document built from string Templates) -
that would give the BSM pages their own visual language, inconsistent with
every prediction/evaluation report elsewhere in the app. Instead this
reuses `ml_report.py`'s generic HTML building blocks
(`_kv_table`/`_data_table`/`_img_tag`/`wrap_html_document`/`_DARK`), so a
BSM report looks like the same family of document as a prediction report.
"""
from datetime import datetime

from .ml_report import _DARK, _data_table, _img_tag, _kv_table, wrap_html_document


def build_bsm_report_html(res, image_paths=None, embed_images=True):
    p = res["params"]
    image_paths = image_paths or {}
    na = "Not available"

    h = []
    h.append("<div style='font-family:Segoe UI, Arial, sans-serif;"
             "color:#1e293b;font-size:13px;'>")
    h.append(f"<h1 style='color:{_DARK};'>Blade Strike Modelling Report</h1>")

    h.append(f"<h2 style='color:{_DARK};'>Inputs</h2>")
    h.append(_kv_table([
        ("Species",                    p["species"]),
        ("Fish body length Lf (m)",    f"{p['lf']:g}"),
        ("Fish body height Bf (m)",    f"{p['bf']:g}"),
        ("Relative fish velocity wf (m/s)", f"{p['wf']:g}"),
        ("Pre-rotation angle α (rad)", f"{p['alpha']:g}"),
        ("Eel critical velocity (m/s)", f"{p['eel_vcrit']:g}"),
        ("Number of blades n",         p["n"]),
        ("Shaft speed N (rpm)",        f"{p['N']:g}"),
        ("Flow rate Q (m³/s)",         f"{p['Q']:g}"),
        ("Tip radius r (m)",           f"{p['r']:g}"),
        ("Hub radius bh (m)",          f"{p['bh']:g}"),
    ]))

    h.append(f"<h2 style='color:{_DARK};'>Derived geometry</h2>")
    h.append(_kv_table([
        ("Fish max length Lmax (m)",   f"{res['Lmax']:.4f}"),
        ("Angular velocity Ω (rad/s)", f"{res['Omega']:.4f}"),
        ("Flow area A (m²)",           f"{res['A']:.4f}"),
        ("Mean axial velocity vm (m/s)", f"{res['vm']:.4f}"),
        ("Blade-tip regime",           res["regime_tip"]),
        ("Blade-tip critical velocity (m/s)", f"{res['vcrit_tip']:.4f}"),
    ]))

    h.append(f"<h2 style='color:{_DARK};'>Results</h2>")
    headers = ["Method", "Pco (%)", "fMR (%)", "Pm (%)", "S (%)"]
    rows = [["CEN", f"{res['Pco_tip'] * 100:.2f}", f"{res['fMR_tip'] * 100:.2f}",
             f"{res['Pm'] * 100:.2f}", f"{res['S'] * 100:.2f}"]]
    if "Pco_obs" in res:
        rows.append(["Observed", f"{res['Pco_obs'] * 100:.2f}",
                     f"{res['fMR_tip'] * 100:.2f}", f"{res['Pm_obs'] * 100:.2f}",
                     f"{res['S_obs'] * 100:.2f}"])
    h.append(_data_table(headers, rows))
    if "Pco_obs" in res:
        h.append(f"<p>Wilson 95% CI on observed collision probability: "
                 f"[{res['wilson_lo'] * 100:.2f}%, {res['wilson_hi'] * 100:.2f}%] "
                 f"(n={p.get('total', na)}, strikes={p.get('strike', na)}).</p>")

    figs = [image_paths.get("pco"), image_paths.get("pm")]
    figs = [f for f in figs if f]
    if figs:
        h.append(f"<h2 style='color:{_DARK};'>Figures</h2>")
        for f in figs:
            h.append(_img_tag(f, embed_images))

    h.append("<p style='color:#64748b;font-size:11px;margin-top:16px;'>"
             f"Generated by StrikeWorks on "
             f"{datetime.now().strftime('%Y-%m-%d %H:%M')}.</p>")
    h.append("</div>")
    return "".join(h)
